name: Practica GHActions Workflow
on:
  push:
    branches: [ master ]

jobs:

  linter_job:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run lint

  cypress_job:

    runs-on: ubuntu-latest
    needs: linter_job

    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: cypress-io/github-action@v2
        id: cypress
        continue-on-error: true
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start

      - run: echo ${{ steps.cypress.outcome }} > result.txt

      - uses: actions/upload-artifact@v2
        with:
          name: result.txt
          path: result.txt

  add_badge_job:

    runs-on: ubuntu-latest
    if: always()
    needs: cypress_job
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: result.txt
      
      - run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
        id: cypress
      
      - uses: ./.github/actions/change_readme/
        id: readme
        with:
          cypress: ${{ steps.cypress.outputs.cypress_outcome }}
      
      - run: | 
            git config user.email "juan.antonio.lis@gmail.com"
            git config user.name "jals-es"
            git pull
            git add .
            git commit --allow-empty -m "Readme" 
            git remote set-url origin https://jals-es:${{ secrets.TOKEN_GITHUB }}@github.com/jals-es/practica_ghactions.git
            git push

  deploy_job:

    runs-on: ubuntu-latest
    needs: cypress_job
    
    steps:
      - uses: actions/checkout@v2

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./